version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      MYSQLHOST: mysql
      MYSQLPORT: 3306
      MYSQL_DATABASE: mydatabase
      MYSQLUSER: myuser
      MYSQLPASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
